name: Build and Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  

      - name: Install AWS SDK for JavaScript
        run: npm install aws-sdk
      
      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
    

      - name: Upload index.js to S3
        uses: aws-actions/aws-upload-file
        with:
          aws-region: your_aws_region  # Replace with your AWS region
          actions: upload
          bucket: your_s3_bucket_name  # Replace with your S3 bucket name
          object: ./lambda/index.js  # Path to your file
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Clean Up (Optional)
        run: rm ./lambda/index.js  